#include <stdio.h>
#define		QUOTECOUNT 10	
//
//------------------------------------------------------------------------------
//	quotes.c  - The home of the Gae of Thrones quotes. 
//	Passed - The quote number, between 0 and QUOTECOUNT
// 	Returns - Pointer to a string containing the quote. 
//
//	Notes: 	This is the static list of quotes, the best ones I could find. 
//		All the single quotes have been removed. 
//		There is one quote with foul language. You have been warned. 
//	Author:	Barry@Condrey.org 
//------------------------------------------------------------------------------
// 
char *get_quote(index) 
int index; 
{
#define QUOTENUM 192

static char *quotelist[]={
"Valar Morghulis.", 
"By what right does the wolf judge the lion?",
"Chaos isnt a pit. Chaos is a ladder.",
"Winter is coming.",
"The Lord of Light wants his enemies burnt. The Drowned God wants his enemies drowned. Why are all the gods such vicious cunts? Where is the god of tits and wine?",
"The more people you love, the weaker you are .... Love no one but your children.",
"On my honor as a Tully, on my honor as a Stark, let him go, or I will cut your wifes throat.", 
"You know nothing, Jon Snow.",
"The man who passes the sentence should swing the sword.",
"What happens when the non-existent bumps against the decrepit? Question for the philosophers.",
"My brother has his sword, and I have my mind. A mind needs books like a sword needs a whetstone.",
"Its not easy being drunk all the time. If it were easy, everyone would do it.",
"I just want to stand on top of the Wall and piss off the edge of the world.",
"Its hard to put a leash on a dog once youve put a crown on its head.",
"Fear cuts deeper than swords.",
"There is only one god and his name is Death. And there is only one thing we say to Death: Not today.", 
"Some old wounds never truly heal, and bleed again at the slightest word.",
"When you play a game of thrones you win or you die.",
"Most men would rather deny a hard truth than face it.",
"The things we love destroy us every time, lad. Remember that.",
"And I have a tender spot in my heart for cripples and bastards and broken things.",
"Why is it that when one man builds a wall, the next man immediately needs to know whats on the other side?",
"When the snows fall and the white winds blow, the lone wolf dies but the pack survives.",
"Nothing burns like the cold.",
"If I look back I am lost.",
"Life is not a song, sweetling. Someday you may learn that, to your sorrow.",
"Give me honorable enemies rather than ambitious ones, and Ill sleep more easily by night.",
"Different roads sometimes lead to the same castle.",
"Every flight begins with a fall.",
"Laughter is poison to fear.",
"The things I do for love.",
"Summer will end soon enough, and childhood as well.",
"I swear to you, sitting a throne is a thousand times harder than winning one.",
"There is no creature on earth half so terrifying as a truly just man.",
"Once you’ve accepted your flaws, no one can use them against you.",
"A lord must learn that sometimes words can accomplish what swords cannot.",
"The man who fears losing has already lost.",
"You cant hammer tin into iron, no matter how hard you beat it, but that doesnt mean its useless.",
"If a man paints a target on his chest, he should expect that sooner or later someone will loose an arrow on him.",
"A craven can be as brave as any man, when there is nothing to fear.",
"A Lannister always pays his debts.",
"The High Septon once told me that as we sin, so do we suffer.",
"Swift as a deer. Quiet as a shadow. Fear cuts deeper than swords. Quick as a snake. Calm as still water.",
"The heart lies and the head plays tricks with us, but the eyes see true.",
"She had put despair and fear aside, as if they were garments she did not choose to wear.",
"We are only human, and the gods have fashioned us for love. That is our great glory, and our great tragedy.",
"You wear your honor like a suit of armor... You think it keeps you safe, but all it does is weigh you down and make it hard for you to move.",
"Why is it always the innocents who suffer most, when you high lords play your game of thrones?",
"All dwarfs may be bastards yet not all bastards are dwarfs.",
"A ruler who hides behind paid executioners soon forgets what death is.",
"Minds are like swords, I do fear. The old ones go to rust.",
"A cold wind was blowing from the north, and it made the trees rustle like living things.",
"A man who wont listen cant hear.",
"You must put these dreams aside, they will only break your heart.",
"I am the fire that burns against the cold, the light that brings the dawn, the horn that wakes the sleepers, the shield that guards the realms of men.",
"Everythings better with some wine in the belly.",
"Never forget what you are. The rest of the world will not. Wear it like armor, and it can never be used to hurt you.",
"He was no dragon, Dany thought, curiously calm. Fire cannot kill a dragon",
"She should be on a hill somewhere, under a fruit tree, with the sun and clouds above her and the rain to wash her clean.",
"The years leech at a mans memories, even those he has vowed never to forget.",
"Only a man whos been burned knows what hell is truly like.",
"Death is so terribly final, while life if full of possibilities",
"Is it so far from madness to wisdom?",
"Love is the bane of honor, the death of duty.",
"A long summer always meant a long winter to come.",
"They’re both bungholes who think they’re too noble to shit",
"You do not steal from the dragon, oh, no. The dragon remembers.",
"Mother, I want to see him fly!",
"Wisdom oft comes from the mouth of babes.",
"Most men would rather deny a hard truth than face it",
"Her lord father had taught her never to steal, but it was growing harder to remember why.",
"Do the dead frighten you?",
"When you find yourself in bed with an ugly woman, the best thing to do is close your eyes and get on with it",
"You are an honest and honorable man...Ofttimes I forget that. I have met so few of them in my life.",
"It seemed cruel for a day to dawn so fair and end so foul as this one promised to.",
"They say nights beauties fade at dawn, and the children of wine are oft disowned in the morning light.",
"I am the shield that guards the realms of men.",
"Folly and desperation are ofttimes hard to tell apart.",
"In life, the monsters win.",
"And for the first time in hundreds of years, the night came alive with the music of dragons.",
"We only make peace with our enemies. Thats why its called making peace.",
"They hate you because you act like youre better than they are.",
"A mad man sees what he sees.",
"Dark wings, dark words.",
"I will not have those I have freed slide back into the chains of slavery. ",
"There must always be a Stark in Winterfell.",
"Expect nothing of Walder Frey, and you will never be surprised.",
"I was never so alive as when I was winning this throne, or so dead as now that I’ve won it.",
"Every flight begins with a fall.",
"A lion doesnt concern himself with the opinions of a sheep.",
"Somewhere off in the distance, a wolf was howling. Crows circled the broken tower, waiting for corn.",
"Nothing holds an edge like Valyrian steel.",
"We’ll shove our swords up Tywin Lannister’s bunghole soon enough.",
"I have a tender spot in my heart for cripples and bastards and broken things.",
"Think carefully before you say them, for once you have taken the black, there is no turning back.",
"Pain is a gift from the gods.",
"Every inn in the city is full, and the whores are walking bowlegged and jingling with each step.",
"Be strong, boy. The gods are cruel.",
"A chain needs all sorts of metals, and a land needs all sorts of of people.",
"A reader lives a thousand lives before he dies.",
"Noseless and Handless, the Lannister Boys.",
"Woman? Is that meant to insult me? I would return the slap, if I took you for a man.",
"All halls lead somewhere. Where there is a way in, there is a way out.",
"The great thing about reading is that it broadens your life.",
"The North remembers.",
"You are grown so very great now, yet the higher a man climbs the farther he has to fall.",
"Valar Morghulis.",
"Even the truest knight cannot protect a king against himself.",
"All men must die",
"It was queer how sometimes a childs innocent eyes can see things that grown men are blind to.",
"Tears arent a womans only weapon.",
"She had never loved him so much as she did in that instant.",
"In the game of thrones, even the humblest pieces can have wills of their own.",
"Why ask for truth when you close your ears to it?",
"Hold yourself.. why Winter is coming.",
"I thank you for calling them off, young ser. I promise you, they would have found me indigestible.",
"Valar Dohaeris.",
"The things I do for love.",
"The next time you raise a hand to me will be the last time you have hands!",
"Its the family name that lives on. Its all that lives on.",
"I learned how to die a long time ago.",
"When dead men and worse come hunting … you think it matters who sits on the Iron Throne?",
"Turn us away, and we will burn you first.",
"A girl gives a man his own name?",
"Your joy will turn to ashes in your mouth.",
"Those are brave men knocking at our door. Lets go kill them!",
"Neither gods nor men will ever compel me to let you turn Casterly Rock into your whorehouse.",
"A dragon is not a slave.",
"Burn them all.",
"If you ever call me sister again, Ill have you strangled in your sleep.",
"The Lannisters send their regards.",
"Watching your vicious bastard die gave me more relief that a thousand lying whores.",
"He could be the first man who sits on that throne in fifty years to actually deserve it.",
"A man with no motive is a man no one suspects. Always keep your foes confused.",
"You wont be a very good hand if you see the word knight and say ""ka-niggit.",
"Let me kill this man for you.",
"When it comes to war I fight for Dorne. When it comes to love, I dont choose sides.",
"I will not become a page in someone elses history book.",
"The world is overflowing with horrible things, but theyre all a tray of cakes next to death.",
"War is war, but killing a man at a wedding, horrid. What sort of monster would do such a thing? As if men need more reasons to fear marriage.",
"Shes gone, I know you dont want to believe it, but she is. Now, go drink until it feels like you did the right thing.",
"A one handed man with no family needs all the help he can get.",
"People learn to love their chains.",
"An unhappy wife is a wine merchants best friend.",
"I shouldnt make jokes. My mother taught me not to throw stones at cripples. But my father taught me, aim for their head.",
"Any man who must say, I am the king, is no true king.",
"The gods love to reward a fool.",
"Hush Hodor! No more Hodoring!",
"Some day Im going to put a sword through your eye and out the back of your skull.",
"Dead rats dont squeak.",
"Your king says he betrayed me for love. I say he betrayed me for firm tits and a tight fit ... and I can respect that.",
"I can always see whats going on beneath a dress. Been at this a long time. I bet when you take that dress off everything stays right where it is. Dont drop an inch.",
"Drinking and lust , no man can match me in these things. I am the god of tits and wine.",
"You wont be a prisoner after today, youll be my wife.",
"I think mothers and fathers made up the gods because they wanted their children to sleep through the night.",
"A man who fights for gold cant afford to lose to a girl.",
"If we die we die, but first we will live.",
"Women in our position must make the best of our circumstances.",
"How am I supposed to sit here planning a war, when youre over there looking like that?",
"A sword swallower through and through.",
"Youre paying for my sins Uncle. Its not fair or right. Ill remember it.",
"I always take figs mid afternoon. Helps move the bowels.",
"Im a monster, as well as a dwarf. You should charge me double.",
"Would it be excessive of me to ask you to save my life twice in a week?",
"My father is dead. And the only parent I have left has no right to call anyone reckless.",
"Any man dies with a clean sword, Ill rape his fu-king corpse!",
"The gods have no mercy, thats why theyre gods.",
"Tears arent a womans only weapon. The best ones between your legs.",
"I much like my head. I dont want to see it removed just yet.",
"Youve forgotten the most important thing about whores. You dont buy them, you only rent them.",
"Has anyone ever told you youre as boring as you are ugly?",
"They will bend the knee or I will destroy them.",
"Theres a king in ever corner now.",
"There are no men like me. Only me.",
"Tell me, which do you favor, your fingers or your tongue?",
"If we do it your way kingslayer, you would win. Were not doing it your way.",
"As impossible as it seems, there was once a time I was unaccustomed to wine.",
"I have never been nothing. I am the blood of the dragon.",
"Tell Lord Tywin winter is coming for him. Twenty thousand northerners marching south to find out if he really does sh*t gold.",
"I did warn you not to trust me.",
"Targareyans wed brothers and sisters for 300 years to keep the bloodline pure.",
"No! You cannot touch me. I am the dragon! I want my crown!",
"Youre the Kings Hand Lord Stark, you will do as I command or Ill find me a hand who will.",
"Very handsome armor. Not a scratch on it.",
"If I get through this without scratching from one end through the other, it will be a miracle.",
"Surrounded by Lannisters. Every time I close my eyes, I see their blond hair and their smug, satisfied faces.",
"War was easier than daughters.",
"Winter may be coming, but Im afraid the same cannot be said for my brother.",
"All the best swords have names you know.",
"Give my regards to the Nights Watch. Im sure it will be thrilling. And if its not, its only for life.",
"I have no interest in hospitality or comfort. Ill stay with Drogo until he fulfills his end of the bargain and I get my crown.",
"Im not trying to honor you, Im trying to get you to run my kingdom while I eat drink and whore my way to an early grave. Dammit, Ned, stand up."}; 

if (index > QUOTENUM) index=1; 

return(quotelist[index]); 

}
